# Generated by Django 2.1.3 on 2020-05-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_auto_20200430_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_case_name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('web_test_result', models.BooleanField(verbose_name='测试结果')),
                ('web_tester', models.CharField(max_length=16, verbose_name='测试负责人')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'web测试用例',
                'verbose_name_plural': 'web测试用例',
            },
        ),
        migrations.CreateModel(
            name='WebCaseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_test_name', models.CharField(max_length=200, verbose_name='测试用例名称')),
                ('web_test_step', models.CharField(max_length=200, verbose_name='测试步骤')),
                ('web_test_objname', models.CharField(max_length=200, verbose_name='测试对象名称描述')),
                ('web_find_method', models.CharField(max_length=200, verbose_name='定位方式')),
                ('web_ev_element', models.CharField(max_length=800, verbose_name='控件元素')),
                ('web_opt_method', models.CharField(max_length=200, verbose_name='操作方法')),
                ('web_test_date', models.CharField(max_length=200, null=True, verbose_name='测试数据')),
                ('web_assert_data', models.CharField(max_length=200, verbose_name='校验数据')),
                ('web_test_result', models.BooleanField(verbose_name='测试结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('WebCase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webtest.WebCase')),
            ],
        ),
    ]
