# Generated by Django 2.1.3 on 2020-05-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcasestep',
            name='web_test_name',
        ),
    ]
