# Generated by Django 2.1.3 on 2020-05-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_auto_20200430_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_name', models.CharField(max_length=64, verbose_name='bug名称')),
                ('bug_detail', models.CharField(max_length=200, verbose_name='bug详情')),
                ('bug_status', models.CharField(choices=[('激活', '激活'), ('已解决', '已解决'), ('已关闭', '已关闭'), ('重新打开', '重新打开')], default='激活', max_length=200, null=True, verbose_name='解决状态')),
                ('bug_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=200, null=True, verbose_name='严重程度')),
                ('bug_creater', models.CharField(max_length=200, verbose_name='bug创建人')),
                ('bug_assign', models.CharField(max_length=200, verbose_name='bug分配人')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'bug管理',
                'verbose_name_plural': 'bug管理',
            },
        ),
    ]
