# Generated by Django 2.1.3 on 2020-04-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200430_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_time',
            new_name='createtime',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_desc',
            new_name='productdesc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='productname',
        ),
    ]
