# Generated by Django 2.1.3 on 2020-04-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200430_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createtime',
            new_name='create_time',
        ),
    ]
