# Generated by Django 2.1.3 on 2020-04-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200430_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productdesc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='product_name',
        ),
    ]
