# Generated by Django 2.1.3 on 2020-04-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apistep',
            name='api_response',
            field=models.CharField(max_length=5000, null=True, verbose_name='响应数据'),
        ),
    ]
