# Generated by Django 2.1.3 on 2020-05-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcasestep',
            name='app_find_method',
            field=models.CharField(max_length=200, null=True, verbose_name='定位方式'),
        ),
        migrations.AlterField(
            model_name='appcasestep',
            name='app_opt_method',
            field=models.CharField(max_length=200, verbose_name='操作方法'),
        ),
    ]
